[phases.setup]
nixPkgs = ["python310"]
aptPkgs = ["libgl1", "libgl1-mesa-glx", "libglib2.0-0", "mesa-utils"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app --workers 1 --threads 8 --timeout 120"
